"""B3 — the incident record as markdown: what ranked, what was proposed, decided and run.

`session.py` has always said the session is "exactly the incident record's input"; this is the
renderer that reads it. The automation server posts it into the brief's Slack thread once a decision
is recorded, so the on-call ends with the postmortem's input already in the channel.

**Investigation-side**, beside the session, and imports nothing from `actions/` — an
investigation-only session renders too, and `tests/integration/test_layer_seam.py`'s rule holds.

**Values from an execution are never reproduced.** A result or an inverse can carry the value a
card masked, and `slack/handlers.approval_sink` stopped printing them for that reason (drift log,
12 Sep). The record names which fields exist, not what they hold. Change diffs render as the brief
renders them: collectors redact secrets at normalization.

**A record, not a channel.** Nothing reads this back to decide anything.
"""

from __future__ import annotations

from typing import Any

from .session import IncidentSession

__all__ = ["render_record"]


def render_record(session: IncidentSession) -> str:
    alert = session.alert
    out = [
        f"# Incident record · {_inline(session.incident_id)}",
        "",
        f"- **Stage:** {session.stage}",
        f"- **Alert:** {_inline(alert.summary)}",
        f"- **Service:** {_inline(alert.service)}",
        f"- **Fired:** {_stamp(alert.fired_at)}",
    ]
    if session.window is not None:
        out.append(f"- **Window searched:** {_stamp(session.window.start)} → {_stamp(session.window.end)}")
    if session.degraded:
        out.append("- **Degraded:** at least one change source was unavailable; this record may be incomplete.")

    out += ["", "## What changed, ranked", ""]
    if not session.candidates:
        out.append("No change touched the blast radius in the window searched.")
    for candidate in session.candidates:
        out.extend(_candidate(candidate, alert))

    if session.narrative:
        out += [
            "",
            "## Narrative",
            "",
            "_Written by the model from the cited evidence. The scores above are computed in code._",
            "",
            session.narrative.strip(),
        ]

    if session.proposal is not None:
        proposal = session.proposal
        out += [
            "",
            "## Proposed action",
            "",
            f"- **Action:** `{_code(proposal.action_id)}`",
            f"- **Declared tier:** {int(proposal.tier)}",
            f"- **Rationale:** {_inline(proposal.rationale)}",
        ]
        if proposal.evidence_ids:
            out.append("- **Evidence cited:** " + ", ".join(f"`{_code(i)}`" for i in proposal.evidence_ids))

    if session.approval is not None:
        approval = session.approval
        out += [
            "",
            "## Decision",
            "",
            f"- **{approval.decision.capitalize()}** by Slack user `{_code(approval.approver)}` at {_stamp(approval.approved_at)}",
            f"- **Action:** `{_code(approval.action_id)}` at tier {approval.tier}",
        ]
        if approval.escalation_reason:
            out.append(f"- **Escalated:** {_inline(approval.escalation_reason)}")

    if session.execution is not None:
        execution = session.execution
        out += [
            "",
            "## Execution",
            "",
            f"- **{'Succeeded' if execution.succeeded else 'Failed'}** at {_stamp(execution.executed_at)}",
        ]
        if execution.error:
            out.append(f"- **Error:** {_inline(execution.error)}")
        fields = sorted(key for key in execution.result if key != "inverse")
        if fields:
            out.append("- **Result fields:** " + ", ".join(f"`{_code(f)}`" for f in fields) + " _(values not reproduced)_")
        if execution.inverse:
            params = sorted((execution.inverse.get("params") or {}).keys())
            out.append(
                f"- **Inverse:** `{_code(execution.inverse.get('action_id'))}`"
                + (" with " + ", ".join(f"`{_code(p)}`" for p in params) if params else "")
                + " _(values not reproduced)_"
            )

    out += ["", "---", f"_Generated by FazerOps at {_stamp(session.created_at)}. This record ran nothing._", ""]
    return "\n".join(out)


def _candidate(candidate: Any, alert: Any) -> list[str]:
    event = candidate.event
    minutes = (alert.fired_at - event.occurred_at).total_seconds() / 60.0
    lines = [
        f"{candidate.rank}. **{_inline(event.resource.kind)} {_inline(event.resource.name)}** — score {candidate.score:.2f} — "
        f"{event.action.value} by {_inline(event.actor.display)}"
        f"{'' if event.actor.resolved else ' (unresolved identity)'}, {minutes:.0f} min before the alert — "
        f"{'in band' if event.in_band else 'out of band'} — evidence `{_code(event.id)}`"
    ]
    if event.diff and event.diff.fields_changed:
        for field in event.diff.fields_changed:
            before = (event.diff.before or {}).get(field)
            after = (event.diff.after or {}).get(field)
            if event.diff.prior_value_captured:
                lines.append(f"   - `{_code(field)}`: {_inline(before)} → {_inline(after)}")
            else:
                lines.append(f"   - `{_code(field)}`: {_inline(after)} _(new value; prior value not captured)_")
    return lines


def _inline(text: Any) -> str:
    """One line. Alert summaries and change values are attacker-influenceable, and a newline in one
    would start a heading or a list item that reads like part of the record."""
    return " ".join(str(text).split())


def _code(text: Any) -> str:
    return _inline(text).replace("`", "'")


def _stamp(moment: Any) -> str:
    return moment.strftime("%Y-%m-%d %H:%M:%S UTC")
